### ISSUE TITLE
Pandoc citations: No space after semicolon with multiple items

### ISSUE THREAD

**Issue by adunning** [retorquere/zotero-citations#13]
Using 0.12.0, if multiple items are selected, they are separated with a semicolon only, omitting the space.

(This package continues to be a lifesaver.)

**Comment by retorquere** [comment]
So that would have to be `[@cite1; @cite2]` rather than `[@cite1,@cite2]`?

**Comment by retorquere** [comment]
Fixed with https://github.com/ZotPlus/zotero-better-bibtex/issues/417, will be released after tests have passed.

**Comment by retorquere** [comment]
BBT 1.6.22 is out (no change required in the atom addon)

**Comment by mjsielerjr** [comment]
I'm still observing this issue using Atom 1.45.0, Zotero-citations 5.2.0

Atom:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/6273555/79915939-bb801a80-83dc-11ea-8fb3-0756884a6225.png">

Word Doc:
![image](https://user-images.githubusercontent.com/6273555/79915986-d05cae00-83dc-11ea-8e61-12d0f702ed53.png)

**Comment by retorquere** [comment]
What version of BBT are you on?

**Comment by mjsielerjr** [comment]
> What version of BBT are you on?

BBT v 5.2.21

**Comment by retorquere** [comment]
I don't get it. The screenshot you show displays the behavior that @adunning deemed desirable (that is, he said he wanted `;<space>` separation rather than `;`).

**Comment by mjsielerjr** [comment]
Sorry, I see now that I misunderstood the original post. I meant to say that when I export the document the citations are "1,2" instead of "1, 2" with a space between the numbers. I'm not sure if that's an issue with this zotero-citations or perhaps it's the issue with the citation .csl file with formatting.

**Comment by retorquere** [comment]
You'd have to ask the pandoc people. I generate `[@cite1; @cite2]`; what pandoc makes of that is out of my hands, unless pandoc expects different input.

If you do have more questions, please open a new issue, adunning is getting mails for everything we say here.

**Comment by mjsielerjr** [comment]
@retorquere,

Thanks, will do. Btw, love your apps. Just donated 10 euros. Cheers!
