### ISSUE TITLE
[JurisM] Could not format References: undefined

### ISSUE THREAD

**Issue by duncdrum** [retorquere/zotero-citations#18]
Tried the visual picker from atom 1.7.1 with Juris-M 4.0.29.M63 and BBT 1.6.45.
The picker can access my library but fails to insert with the following.
![screenshot 2016-04-15 18 43 10](https://cloud.githubusercontent.com/assets/6205362/14568559/f9edd17c-0339-11e6-82b0-b93d555a1aa5.png)

Has anybody tried this configuration? A fix for this seems to have gone out for regular Zotero.

**Comment by retorquere** [comment]
Juris-M versions below 4.0.29.7 are not compatible with BBT. A new version of Juris-M should be out soon, and once it is, I'll release the updated BBT that supports it.
