### ISSUE TITLE
JS error: "Could not format references: this.getStyle is not a function"

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#22]
I used the plugin before (and it worked), but now I get the error above whenever I try to pick an item.

Atom 1.8.0, Zotero Standalone 4.0.29.10, ZBB 1.6.63.

**Comment by retorquere** [comment]
Can you do the following:

1. in BBT prefs, advanced enable extended debugging
2. trigger the error from atom
3. in Zotero, from the gear menu, select "send BBT error"
4. post the resulting ID (displayed in red) here

**Comment by rmzelle** [comment]
4C8X9M2E

**Comment by retorquere** [comment]
Can you try this test version of BBT: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.63-circle-2536.xpi

**Comment by rmzelle** [comment]
No luck (I didn't restart Atom, though).

**Comment by retorquere** [comment]
Restatring atom shouldn't be necessary. Can you submit a new debug log and post the new ID?

**Comment by rmzelle** [comment]
PSRGAT7J

**Comment by retorquere** [comment]
I have my defense tomorrow; I'm going to look at this in the weekend.

**Comment by rmzelle** [comment]
Good luck en veel success!

**Comment by retorquere** [comment]
If it ends well, a fair amount of luck will have been involved.

Bedankt!

**Comment by retorquere** [comment]
That version appears to not have the changes I made. Really strange. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.63-circle-2540.xpi ?

**Comment by rmzelle** [comment]
Thanks, that fixed it! (I now again get a proper citation with the picker, like `[\(Abbott et al., 2007\)](@abbott_generic_2007)`)

**Comment by retorquere** [comment]
Not as tight as I had wanted it to be, but well enough to graduate with honors.

**Comment by retorquere** [comment]
.64 is out with this fix btw.
