### ISSUE TITLE
Suggest Zotero might be closed if connection fails

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#24]
When I e.g. run "Scan" with Zotero Standalone closed, I get the following popup:

![image](https://cloud.githubusercontent.com/assets/77951/16010192/14291cda-314e-11e6-9fce-4592a282c4a1.png)

Since it's probably rather common that the user forgets to open, or accidentally closes Zotero Standalone, it would be nice to have a nicer message that says something like "zotero-citations couldn't connect to Zotero Standalone. Make sure Zotero is open and that the Zotero Better Bib(La)Tex extension is installed and enabled."

(seems relatively straightforward to do with the standard package https://github.com/atom/notifications)

**Comment by retorquere** [comment]
Do you know a package that already uses this? The docs for the notifications package are a little scarce on detail on how to actually use this.

**Comment by rmzelle** [comment]
Looks like https://github.com/AtomLinter/linter-eslint/ does (see https://github.com/atom/notifications/issues/104 and https://github.com/AtomLinter/linter-eslint/search?utf8=%E2%9C%93&q=%22worker+died%22&type=Code).
