### ISSUE TITLE
Give examples of each format in documentation

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#26]
It would be great if the README would give examples of the various formats. (happy to provide a PR for this)

**Comment by rmzelle** [comment]
I'm also experiencing two issues with the current result:

1) The DOI link is incorrectly escaped. I'm pretty sure `<http://doi.org/10.1128/genomeA.00323\-13>` should just be `<http://doi.org/10.1128/genomeA.00323-13>` (pandoc converts the former to http://doi.org/10.1128/genomeA.00323/-13, which gives a 404).
2) The in-text citation has this link: `http://.../genomics/@brown_genome_2013`, which also gives a 404. If I change this to `http://.../genomics/#brown_genome_2013`, the anchor does work. Is there a way to either avoid the link, or to get a correct anchor. Or is the only way to switch to the `[(Heyns, 2014)](#heyns2014)` format? (which would mess with my internal anchors)

**Comment by retorquere** [comment]
OK, in order:

0) Looks like I never got around to pandoc scanning, but I also don't remember what prompted me to start, or what it would look like.
1) I'll have to talk to the citeproc maintainers about that, it looks like I don't get to choose how that's escaped.
2) I don't understand the last problem ("the in-text citation has this link"). The @ links should be regular definition style links, are they expanded to "http..." by the plugin or by something else?

These issues are really separate problems, could you split them into separate issues?

If PR means pull request, then yes, absolutely appreciated.

**Comment by rmzelle** [comment]
For 2), the produced HTML for the in-text citation looks like: `<a href="@brown_genome_2013">(Brown et al., 2013)</a>`

Shouldn't this be `<a href="#brown_genome_2013">(Brown et al., 2013)</a>` (with a hash)?

**Comment by retorquere** [comment]
What processor do you use to convert the markdown to html?

**Comment by rmzelle** [comment]
> These issues are really separate problems, could you split them into separate issues?

Yeah, sorry. I'll pull them apart.

**Comment by rmzelle** [comment]
> What processor do you use to convert the markdown to html?

pandoc.

**Comment by retorquere** [comment]
When you're done splitting the issues, could you either close this issue, or edit out the parts that are no longer relevant?

**Comment by rmzelle** [comment]
Done.

**Comment by rmzelle** [comment]
(can you delete all comments except the first?)

**Comment by retorquere** [comment]
I don't honestly know what the YAML format would look like. I must have started this on someone's prompt but never finished it, and I can't find any previous issues that speak of this feature.

**Comment by rmzelle** [comment]
The ticket for that is now https://github.com/retorquere/zotero-citations/issues/29. Would it make sense to just remove the settings option, then?

**Comment by retorquere** [comment]
I've added the pandoc scanner instead.

**Comment by retorquere** [comment]
And I've updated the README with samples.
