### ISSUE TITLE
Incorrect escaping of DOIs

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#27]
DOI links are incorrectly escaped. I'm pretty sure `<http://doi.org/10.1128/genomeA.00323\-13>` should just be `<http://doi.org/10.1128/genomeA.00323-13>` in the following scanned result (pandoc converts the former to http://doi.org/10.1128/genomeA.00323/-13, which gives a 404):

```
This published genome [\(Brown et al., 2013\)](@brown_genome_2013)

[#bibliography]: #start

[@brown_genome_2013]: #brown_genome_2013 "Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. (2013). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_(3), e00323-13. http://doi.org/10.1128/genomeA.00323-13"

<a name="brown_genome_2013"></a>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. \(2013\). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_\(3\), e00323\-13. <http://doi.org/10.1128/genomeA.00323\-13>

[#bibliography]: #end
```

**Comment by retorquere** [comment]
Can you try 0.16.0 with [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2551.xpi) version of BBT?

**Comment by rmzelle** [comment]
Different problem now :)

The output is now:

```md
[\(Brown et al., 2013\)](#@brown_genome_2013)

[#bibliography]: #start

<a name="@brown_genome_2013"/>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. \(2013\). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_\(3\), e00323\-13. [http://doi.org/](http://doi.org/)10.1128/genomeA.00323\-13

[#bibliography]: #end
```

with `[http://doi.org/](http://doi.org/)10.1128/genomeA.00323\-13`

**Comment by retorquere** [comment]
Son of a... citeproc makes some "interesting" choices on how to generate output. Try this: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2553.xpi

The pick&scan (and drag&drop) did change format. Too many problems with the previous format.

**Comment by rmzelle** [comment]
Close, but no cigar:

`http://doi.org/[10.1128/genomeA.00323\-13](http://dx.doi.org/10.1128/genomeA.00323-13)`

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2554.xpi ?

**Comment by rmzelle** [comment]
Looks good!

```
[\(Brown et al., 2013\)](#@brown_genome_2013)

[#bibliography]: #start

<a name="@brown_genome_2013"/>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. \(2013\). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_\(3\), e00323\-13. [10.1128/genomeA.00323\-13](http://dx.doi.org/10.1128/genomeA.00323-13)

[#bibliography]: #end
```

Converting that with http://pandoc.org/try/ to HTML 5 gives:

```
<p><a href="#@brown_genome_2013">(Brown et al., 2013)</a></p>
<p><a name="@brown_genome_2013"/>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. (2013). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. <em>Genome Announcements</em>, <em>1</em>(3), e00323-13. <a href="http://dx.doi.org/10.1128/genomeA.00323-13">10.1128/genomeA.00323-13</a></p> 
```

**Comment by retorquere** [comment]
Can you try with a reference that has a full doi link instead of just the doi?

**Comment by rmzelle** [comment]
With a string like "http://doi.org/10.1111/j.1567-1364.2009.00537.x", it gives:

```
[\(Abbott, Zelle, Pronk, & Van Maris, 2009\)](#@abbott_copy_2009)

[#bibliography]: #start

<a name="@abbott_copy_2009"/>Abbott, D. A., Zelle, R. M., Pronk, J. T., & Van Maris, A. J. A. \(2009\). Copy \- Metabolic engineering of Saccharomyces cerevisiae for production of carboxylic acids: current status and challenges. _FEMS Yeast Research_, _9_\(8\), 1123–1136. [http://doi.org/10.1111/j.1567\-1364.2009.00537.x](http://dx.doi.org/http://doi.org/10.1111/j.1567-1364.2009.00537.x)

[#bibliography]: #end
```

That this fails (`[http://doi.org/10.1111/j.1567\-1364.2009.00537.x](http://dx.doi.org/http://doi.org/10.1111/j.1567-1364.2009.00537.x)`, which renders as [http://doi.org/10.1111/j.1567\-1364.2009.00537.x](http://dx.doi.org/http://doi.org/10.1111/j.1567-1364.2009.00537.x)) isn't surprising though, since the default APA style prepends "http://doi.org/" to every DOI (https://github.com/citation-style-language/styles/blob/d2a191567fcab44bdb2474ab778f5878af84bf01/apa.csl#L139).

I think Zotero translators all try to save just the identifier bit ("10.1111/j.1567-1364.2009.00537.x") in the DOI field.

**Comment by retorquere** [comment]
OK, so this could count as decent behavior then?

**Comment by rmzelle** [comment]
I couldn't find any item in my 700+ item Zotero library that has a full DOI URL instead of just the identifier, so yeah, I think it's fine. CSL styles also often assume that this is the case (because different styles need different prefixes, like "doi:", "DOI:", or "http://doi.org/").

**Comment by rmzelle** [comment]
(by the way, do you know where the domain address "http://dx.doi.org/" in `[10.1111/j.1567\-1364.2007.00242.x](http://dx.doi.org/10.1111/j.1567-1364.2007.00242.x)` comes from? Your code, or citeproc-js?

Relatively recently "doi.org" has become the preferred resolver address, and "https" is probably preferable over "http", so it would be nice to change this to "https://doi.org".)

**Comment by retorquere** [comment]
I think that's me. https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2572.xpi should be better.

**Comment by rmzelle** [comment]
Just tested it. Perfect, thanks.

**Comment by retorquere** [comment]
OK, waiting for confirmation on #522, and then a new release goes out.
