### ISSUE TITLE
Scan mode setting doesn't seem to have an effect

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#29]
I'm entering citations in the "atom-zotero-citations" format (e.g. `[\(Brown et al., 2013\)](@brown_genome_2013)`), but I get the exact same result with Scan, regardless of whether the "Scan mode" setting is set to "markdown" or "pandoc":

```
This published genome [\(Brown et al., 2013\)](@brown_genome_2013)

[#bibliography]: #start

[@brown_genome_2013]: #brown_genome_2013 "Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. (2013). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_(3), e00323-13. http://doi.org/10.1128/genomeA.00323-13"

<a name="brown_genome_2013"></a>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. \(2013\). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_\(3\), e00323\-13. <http://doi.org/10.1128/genomeA.00323\-13>

[#bibliography]: #end
```

The setting description says that selecting "pandoc" should give "Pandoc-compatible inline YAML", but it currently doesn't.

**Comment by retorquere** [comment]
That particular format wouldn't have worked (the previously supported formats were either `[\(Brown et al., 2013\)](#brown_genome_2013)` or `[\(Brown et al., 2013\)][@brown_genome_2013)`), but the format has changed to be `[\(Brown et al., 2013\)](#@brown_genome_2013)` or `[\(Brown et al., 2013\)](?@brown_genome_2013)` (either will work), due in the next release when I have the BBT side in order.
