### ISSUE TITLE
Functional links for multi-cites

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#30]
This is probably very hard to implement, but I figured it's still a valid feature request :).

The current version of "zotero-citations" generates this:

single cite:

Markdown: `[\(Brown et al., 2013\)](#@brown_genome_2013)`
Rendered: [(Brown et al., 2013)](#@brown_genome_2013)

multiple cite:

Markdown: `[\(Abbott et al., 2007; Zelle, Shaw, & van Dijken, 2014\)](?@zelle_method_2014,abbott_generic_2007)`
Rendered: [(Abbott et al., 2007; Zelle, Shaw, & van Dijken, 2014)](?@zelle_method_2014,abbott_generic_2007)

Ideally, the individual cites would have their own links and targets. Something like:

Markdown: 
`([Abbott et al., 2007](#@abbott_generic_2007); [Zelle, Shaw, & van Dijken, 2014](#@zelle_method_2014))`
Rendered: ([Abbott et al., 2007](#@abbott_generic_2007); [Zelle, Shaw, & van Dijken, 2014](#@zelle_method_2014))

I guess the hard part is that in `([Abbott et al., 2007](#@abbott_generic_2007); [Zelle, Shaw, & van Dijken, 2014](#@zelle_method_2014))`, the order of the individual items, and the affixes (the outer "(" and ")") and delimiter (";"), all depend on the chosen citation style and would have to be updated during the Scan.

**Comment by retorquere** [comment]
The problem with this is that on re-scan, I can't distinguish between what was first `[\(Abbott et al., 2007; Zelle, Shaw, & van Dijken, 2014\)](?@zelle_method_2014,abbott_generic_2007)`, and what was entered by the user as `([Abbott et al., 2007](#@abbott_generic_2007); [Zelle, Shaw, & van Dijken, 2014](#@zelle_method_2014))`. The two are not semantically the same, and the citation processor will do different things.

**Comment by rmzelle** [comment]
Yeah, I understand the trouble.

Maybe you can leave this open, in case it inspires somebody to come up with an ingenious solution?

**Comment by retorquere** [comment]
I've dropped the pure-markdown support. Picking works now but you'll need something like pandoc to do citation processing.
