### ISSUE TITLE
Use opening/closing anchor tags?

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#32]
Both Google Chrome and IE 11 insist on extending the closed anchor tag until the next anchor tag begins:

![image](https://cloud.githubusercontent.com/assets/77951/16244956/983fbc0c-37cc-11e6-867d-1f25e3e10a4e.png)

It's fixed if I change the `<a name="@brown_genome_2013"/>` to `<a name="@brown_genome_2013"></a>` by hand in the Scan output below:

```
[#bibliography]: #start

<a name="@brown_genome_2013"/>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. \(2013\). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_\(3\), e00323\-13. [10.1128/genomeA.00323\-13](http://dx.doi.org/10.1128/genomeA.00323-13)

[#bibliography]: #end
```

Would that be an acceptable change for the Scan output format? It

**Comment by retorquere** [comment]
Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2559.xpi

**Comment by retorquere** [comment]
Sorry, don't try that one, that was for a different issue, a new build is coming up.

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2563.xpi should address both #31 and #32, can you check?

**Comment by rmzelle** [comment]
Great, thanks, v2563 fixes this issue. The now produced `<a name="..."></a>` renders correctly in IE11 and Chrome.

```
[#bibliography]: #start

<a name="@abbott_generic_2007"></a>Abbott, D. A., Knijnenburg, T. A., De Poorter, L. M. I., Reinders, M. J. T., Pronk, J. T., & Van Maris, A. J. A. \(2007\). Generic and specific transcriptional responses to different weak organic acids in anaerobic chemostat cultures of Saccharomyces cerevisiae. _FEMS Yeast Research_, _7_\(6\), 819–833. [10.1111/j.1567\-1364.2007.00242.x](http://dx.doi.org/10.1111/j.1567-1364.2007.00242.x)

<a name="@brown_genome_2013"></a>Brown, S. D., Klingeman, D. M., Johnson, C. M., Clum, A., Aerts, A., Salamov, A., … Froehlich, A. C. \(2013\). Genome Sequences of Industrially Relevant Saccharomyces cerevisiae Strain M3707, Isolated from a Sample of Distillers Yeast and Four Haploid Derivatives. _Genome Announcements_, _1_\(3\), e00323\-13. [10.1128/genomeA.00323\-13](http://dx.doi.org/10.1128/genomeA.00323-13)

<a name="@zelle_method_2014"></a>Zelle, R. M., Shaw, A. J., & van Dijken, J. P. \(2014, May 16\). Method for acetate consumption during ethanolic fermentation of cellulosic feedstocks. Retrieved from <https://patentscope.wipo.int/search/en/WO2014074895>

[#bibliography]: #end
```

**Comment by rmzelle** [comment]
(greatly appreciate all your work on this, by the way!)

**Comment by retorquere** [comment]
my pleasure

**Comment by retorquere** [comment]
This is the last of a batch -- I'm going to wait for a little bit to get confirmation whether  https://github.com/retorquere/zotero-better-bibtex/issues/522 is resolved, and then I'll get a new BBT release.
