### ISSUE TITLE
Multiple pickers pop up

### ISSUE THREAD

**Issue by oztalha** [retorquere/zotero-citations#33]
Two pickers pop up instead of one since I upgraded to 0.16.0.
It still works but annoying to have an extra, and it does not disappear.
When I pick something with the second picker, that still stays on the screen:
<img width="856" alt="screen shot 2016-06-22 at 3 23 59 pm" src="https://cloud.githubusercontent.com/assets/5094153/16280535/fe3aae92-388d-11e6-8dfc-b9e9123a17ba.png">

After calling the picker for inserting a second citation:
<img width="885" alt="screen shot 2016-06-22 at 3 24 17 pm" src="https://cloud.githubusercontent.com/assets/5094153/16280541/0979ec32-388e-11e6-9c76-9c4f0e8009d2.png">

I called the picker via MS Word and it worked as expected (single picker showed up). So, I believe the problem is on the zotero-citations part.

**Comment by retorquere** [comment]
Are there any errors in the atom console?

**Comment by oztalha** [comment]
Interesting. The extra picker issue disappeared. I just have the other issue that `scan` does nothing. The error in the console is
<img width="427" alt="screen shot 2016-06-22 at 5 14 11 pm" src="https://cloud.githubusercontent.com/assets/5094153/16283971/1715025a-389d-11e6-8081-bc23565f3c43.png">

**Comment by retorquere** [comment]
I've published 0.17 which should give a little more detail in the log on what happens.

**Comment by oztalha** [comment]
Hm, thanks but I cannot update:

1. Zotero-citations 0.16.0 is installed.
2. Click on upgrade button.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1


### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709

TypeError: Cannot read property 'substr' of null
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:709:80
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:51
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:403:20
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:09.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.19
jupyter-notebook, v0.0.9
markdown-preview-plus, v2.4.0
terminal-plus, v0.14.5

# Dev
No dev packages
```


<img width="863" alt="screen shot 2016-06-22 at 5 39 59 pm" src="https://cloud.githubusercontent.com/assets/5094153/16284706/762469ae-38a0-11e6-883c-db1a1b1cb122.png">

**Comment by retorquere** [comment]
You'd have to take that up with the settings-view maintainer, that's where
the error is happening.

**Comment by oztalha** [comment]
Ok, managed to install with `apm install zotero-citations` command via terminal. Here is the output
<img width="445" alt="screen shot 2016-06-22 at 6 36 22 pm" src="https://cloud.githubusercontent.com/assets/5094153/16286119/5e49d73a-38a8-11e6-9abd-f381d43f860d.png">

**Comment by retorquere** [comment]
That would indicate the directory that sync-request is trying to write to is read-only, but I think I have a workaround. Try upgrading to 0.18

**Comment by oztalha** [comment]
It appears that you fixed the issue in line 61, but now another one caught at line 248: <img width="432" alt="screen shot 2016-06-23 at 10 58 12 am" src="https://cloud.githubusercontent.com/assets/5094153/16308072/9df63606-3931-11e6-82f8-b78e328fd0b7.png">

**Comment by retorquere** [comment]
Not really fixed, I moved around some code and the error moved with it.

Can you try replacing `/Users/toz/.atom/packages/zotero-citations/lib/schomd.coffee` with https://gist.github.com/11992f34cdb90c0eedfd24ab4d248d2c, restart atom, install https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.65-circle-2587.xpi, restart Zotero, and then try again?

**Comment by retorquere** [comment]
I have published a new version with these changes of both this package and BBT.

**Comment by retorquere** [comment]
The settings-view problem happens with more packages BTW: https://github.com/atom/settings-view/issues/766
