### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by cjpoor** [retorquere/zotero-citations#37]
Hi Emiliano,
zotero-citations for Atom has not been updating for some time.
Below is the latest error report.
Thanks,
Chris.

> deasync@0.1.8 install /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-116910-16648-xum21y/node_modules/zotero-citations/node_modules/deasync
> node ./build.js

/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-116910-16648-xum21y
`-- (empty)

/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-116910-16648-xum21y
`-- (empty)

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-116910-16648-xum21y/package.json'
npm WARN apm-install-dir-116910-16648-xum21y No description
npm WARN apm-install-dir-116910-16648-xum21y No repository field.
npm WARN apm-install-dir-116910-16648-xum21y No README data
npm WARN apm-install-dir-116910-16648-xum21y No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Volumes/Toshiba_2TB_Ext/Applications/Writing/Atom.app/Contents/Resources/app/apm/bin/node" "/Volumes/Toshiba_2TB_Ext/Applications/Writing/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/christopherpoor/.atom/.apm/.apmrc" "--userconfig" "/Users/christopherpoor/.atom/.apmrc" "install" "/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/d-116910-16648-yir3e6/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.1.8 install: `node ./build.js`
npm ERR! Exit status -2
npm ERR! 
npm ERR! Failed at the deasync@0.1.8 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deasync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-116910-16648-xum21y/package.json'
npm WARN apm-install-dir-116910-16648-xum21y No description
npm WARN apm-install-dir-116910-16648-xum21y No repository field.
npm WARN apm-install-dir-116910-16648-xum21y No README data
npm WARN apm-install-dir-116910-16648-xum21y No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Volumes/Toshiba_2TB_Ext/Applications/Writing/Atom.app/Contents/Resources/app/apm/bin/node" "/Volumes/Toshiba_2TB_Ext/Applications/Writing/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/christopherpoor/.atom/.apm/.apmrc" "--userconfig" "/Users/christopherpoor/.atom/.apmrc" "install" "/private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/d-116910-16648-yir3e6/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! deasync@0.1.8 install: `node ./build.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the deasync@0.1.8 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deasync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/99/n4khbrf10cz3mk15pb3cpxsh0000gn/T/apm-install-dir-116910-16648-xum21y/npm-debug.log
npm ERR! code 1

**Comment by 7Moses** [comment]
Me too, 

I am using 1.12.0-beta3 and zotero-citations 0.19.0, getting this bug message for z-c  

"Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."

**Comment by cjpoor** [comment]
It's OK anyway, because one can use Zotero's Quick Copy functionality https://www.zotero.org/support/creating_bibliographies

**Comment by retorquere** [comment]
I still haven't figured out a way to lock the UI in a cross platform way while the processing changes. I'm not comfortable with starting the processing while the editor is unlocked because this addon will replace the whole document with its results, so any edits made while it runs will be blithely overwritten.

**Comment by cjpoor** [comment]
Ok. Thanks. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by retorquere** [comment]
It should now update, but at the cost of the scanner. I need to re-do the scanner to make it work now I can't do sync requests.
