### ISSUE TITLE
Zotero Citations: Scan does not make a bibliography

### ISSUE THREAD

**Issue by ostrokach** [retorquere/zotero-citations#38]
I have a markdown document with several citations:

```
# Hello
[](#@niu_protein-structure-guided_2016)

# World
[](#@brown_genome_2013)

[#bibliography]: #
```

The citations were inserted using copy-paste from Zotero. 

After running "Zotero Citations: Scan", I get the following:

```
# Hello
[??](#@niu_protein-structure-guided_2016)

# World
[??](#@brown_genome_2013)

[#bibliography]: #start

[object Object]

[#bibliography]: #end
```

I read the readme and previous issues, but can't figure out what I am doing wrong.

-----

Linux Mint 18
Atom 1.11.2

**Comment by rmzelle** [comment]
It's my understanding that zotero-citations current latest version (0.19.0) is broken with Atom versions of 1.8 and above. See https://github.com/retorquere/zotero-citations/issues/35

**Comment by retorquere** [comment]
I've temporarily disabled the scanner while I figure out a way to safely do the scan. I was doing a number of sync requests and atom frowns upon those these days.
