### ISSUE TITLE
Zotero-Citations plugin is dead?

### ISSUE THREAD

**Issue by dixonge** [retorquere/zotero-citations#39]
four months, no fix - should we presume this plugin is DOA?

**Comment by retorquere** [comment]
Not DOA (as it's well after arrival), but there's problems for which I currently don't know a fix, and all the time I gave is currently going towards the zotero 5.0 port. It's currently not getting the attention it requires, that is true, and this is likely to remain so until the 5.0 port is done, sorry.

**Comment by dixonge** [comment]
Well, it's DOA if you think of it in terms of an ambulance arriving at a hospital :)

I don't know what the '5.0 port' is, but it doesn't sound like this plugin will be working in the near future. Are there any alternative ways of getting Zotero citations into Atom?

**Comment by retorquere** [comment]
Zotero 5.0 is a full rewrite; everything changes and this affects BBT (the counterpart to this addin) tremendously. I might be able to avoid rewriting all of BBT, but it's a major effort just to get BBT to do what it did under 4.X.

I don't know of any other way to get citations into atom. I think I could remove the bibliography scanner and accept the risk that the citation would end up in an odd place if you move the cursor while reference retrieval is busy, but for the bib scanner that's too much of a risk for me.

**Comment by oztalha** [comment]
As I had noted earlier, I believe zotero-citations could be very helpful even if it is used only to invoke the zotero picker (preferably with a hot-key assigned). Then one can simply call pandoc manually (terminal-plus might come handy), this is what I've been doing until last week. Yet, I couldn't get even the zotero picker show up now.

**Comment by retorquere** [comment]
I have published 0.19.1 which disables the scanner but re-enables the picker. Note that you can now move about in the editor even while the picker is open and the picker will blindly insert the references where the cursor is, or over the selected text if any.
