### ISSUE TITLE
Add picked items to bib file?

### ISSUE THREAD

**Issue by michaelaye** [retorquere/zotero-citations#41]
I am opening the issue here, because I understand now that I possibly had wrong expectations of how things work between better-bibtex and zotero-citations.

Possibly, my thinking is a feature request, not an actual bug, here's what I wanted to happen:

* To avoid having a huge .bib file, I only want the files that I actually cite in my .bib file.
* Starting with a collection of 2 in zotero app, I export this collection into my latex doc folder, keeping it updated. Double-checked that it's setup in Better-Bibtex preferences as well.
* Confirmed that adding an entry to the collection updates the bib file inside my latex document folder, so that all works well.
* I was hoping though, that when I use atom's zotero-picker, that this entry could be added to the bib file as well, avoiding having to do edits on the zotero side, when I already did the citation inside atom. Is that not possible? I understand that possibly the zotero-citations plugin cannot update a collection inside the zotero-app, but what if I don't care? I just would like to use atom and it's zotero-picker for doing citations, and have the plugin collect what's needed and add it to the current .bib file, is that possible somehow?

My versions are all the most recent ones, as I only recently tried out Zotero, coming from the well-working but no-API-having Papers.app.

Thanks for your great work!

**Comment by michaelaye** [comment]
Additional question: Assuming that my above pipeline doesn't work/exist, is it possible to have the atom plugin to scan for citation keys and copy them over into a new .bib file? That would solve everything as well, right?

**Comment by retorquere** [comment]
The above pipeline doesn't exist; I can't know what collection the picked reference would need to be added to. It would in principle be possible to have the plugin scan for references (there's a mode where it does so already for a different use-case), but again, I wouldn't know what collection they'd need to be added to.

**Comment by michaelaye** [comment]
ok, so the only way to use the Atom-Zotero setup then, if to remove manual management on the Zotero side, is to have the full library exported at all times, correct?

**Comment by retorquere** [comment]
Currently, yes, that is correct.

**Comment by michaelaye** [comment]
ok, thanks.
