### ISSUE TITLE
Could not format references: style.getCiteProc is not a function

### ISSUE THREAD

**Issue by ecx2093** [retorquere/zotero-citations#42]
When I pull up the visual picker from within atom, I can select my references but when I hit enter to add them to my text the zotero standalone app pops up with the following error

> [JavaScript Application]
> Could not format references: style.getCiteProc is not a function

I have atom version 1.12.7, zotero v 4.0.29.15, and better Bib(La)Tex 1.6.97 installed and running

**Comment by retorquere** [comment]
Can you install [this test version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.97-atom-42-3756.xpi), enable extended debugging in BBT, and submit a BBT debug log after this happens?
