### ISSUE TITLE
Works with new better-bibtex and Zotero 5?

### ISSUE THREAD

**Issue by werunom** [retorquere/zotero-citations#43]
Since the better-bibtex is in its alpha stage for Zotero 5, would you being updating this package as well? Or does this works fine with the pre-releases you have provided? 

Thought of asking because this package hasnt been updated and better-bibtex is in its early phase.

**Comment by retorquere** [comment]
zotero-citations depends on the [CAYW and SCHOMD](https://trello.com/b/OpJQyVTP/better-bibtex-for-zotero-5) features, which are not completed yet in BBT5.

**Comment by werunom** [comment]
Fine. Will wait for better-bibtex release then. But, I definitely think this package is an essential connector to bibliography if one is using atom as text-editor (either of pandoc or latex). 

NB - Will keep the issue open so that others need not open parallel threads. If you think otherwise, please feel free to close it.

**Comment by retorquere** [comment]
Nope, that's perfectly fine.

**Comment by floriandierickx** [comment]
As a short note here, I want to point to a less functional, but somehow effective, temporary replacement while better bibtex is in development: you could use https://atom.io/packages/autocomplete-bibtex, it auto-completes bibtex keys based on a .bib file. It's not as versatile (no title, keyword, ... search), but it can do part of the job in the meantime. If you know about other atom extentions using .bib files with similar functionality, I'll be glad to know. For the rest, good writing to all, be it text, code or citations :)

**Comment by bwiernik** [comment]
@retorquere With BBT released, is this plugin now compatible with Zotero 5 or should I mark it not yet compatible on the plugins wiki page?

**Comment by retorquere** [comment]
It's fully compatible.

**Comment by retorquere** [comment]
That is, BBT is fully compatibe -- I am not wholly sure what the state of this atom plugin is.

**Comment by retorquere** [comment]
Picking works now
