### ISSUE TITLE
[question] Status of atom plugin

### ISSUE THREAD

**Issue by duncdrum** [retorquere/zotero-citations#44]
I stuck to FF ESR to keep my workflow (Jurism, Atom, BBL) from running for a while but it's finally dead Jim. Moving to the new and much impoverished hotness that is FF quantum and Zot5 the plugin no longer works: 

Now with:
Atom `1.23.3`
Jurism-standalone `5.0.17.3`
BBL `5.0.78`
zot-cit `0.19.1`
on macOS 10.13.2

```
could not connect to Zotero
```

should I switch to autocomplete+, any other tips for where to go from here?

**Comment by retorquere** [comment]
I'm afraid it's bad news all around. The atom plug in probably doesn't work, and Juris-M is untested: https://github.com/Juris-M/zotero/issues/34

**Comment by duncdrum** [comment]
@retorquere I figured as much about Jurism, not sure how I could help there. 

but if the atom-plugin is abandoned I would suggest archiving the repo and pointing to https://atom.io/packages/autocomplete-bibtex instead. It seems to do a reasonably good job with my freshly exported bbl library :wink:

**Comment by retorquere** [comment]
and untested very likely means it will have substantial problems. Everything about Zotero has changed, so when I can't run my test suite, I can't assume it works nor can I support it. As soon as Juris-M launches in my test suite I'll be happy to start the work of making bbt compatible, but until that time, there's nothing I can do.

**Comment by retorquere** [comment]
Picking should work now
