### ISSUE TITLE
please confirm if CAYW picking works in Atom 1.27

### ISSUE THREAD

**Issue by JackDougherty** [retorquere/zotero-citations#45]
Sorry if I'm dense, but am not able to make this work:
"executing 'Zotero Citations: Pick' will call up a graphical picker which will insert these for you"

I have done the following:
- read this page: https://retorque.re/zotero-better-bibtex/cayw/
- installed current version of Better BibTeX in current version of Zotero standalone
- Zotero settings: Export > Quick Copy > Better BibTex Citation Key Quick Copy; Citation Key format = pandoc
- installed zotero-citations v1.0.0 in Atom v1.27.1

Please confirm if the cite-as-you-write picker works. If yes, how do I "execute" it? I don't see it anywhere in the menu, nor in autocomplete options as I type. Thanks

**Comment by retorquere** [comment]
I don't know if it currently works, I haven't worked on it in a long while. The BBT end works, but this end probably needs attention. I'm currently swamped though, so this is not something I can look at right now.

**Comment by JackDougherty** [comment]
Understood. Thanks for all of your work on BBT, which is the more important piece. I can always copy and paste the cite keys.

**Comment by rhaynes74** [comment]
Hi Jack - did you manage to make this work.  I have 1.27.2 and it doesn't seem to work.  It did work on a 1.26.x version but I haven't used it in a while.

**Comment by JackDougherty** [comment]
I followed installation instructions but get stuck [here](https://github.com/retorquere/zotero-citations#visual-picking-of-citations):

"If you don't feel like typing citations out (and let's be honest, you don't), executing 'Zotero Citations: Pick' will call up a graphical picker which will insert these for you, formatted and all."

**Comment by retorquere** [comment]
I've just tested it and it works. You must have Zotero with BBT installed running, but then in Atom you call up the command palette (ctrl-shift-P on linux) and select "Zotero Citations: Pick", and the citation picker from Zotero will pop up. There are ways in Atom to set keyboard shortcuts (the command is `zotero-citations:pick`), but I don't know how that works these days.
