### ISSUE TITLE
Remove the @ prefix

### ISSUE THREAD

**Issue by lezuber** [retorquere/zotero-citations#47]
Hi,
thanks for the great plugin!
Is there any way to paste citation-keys without the "@" prefix, to cite in latex?

Best
Lenz

**Comment by retorquere** [comment]
You can set the `Quick copy/drag-and-drop` format to `Cite Keys`.

**Comment by retorquere** [comment]
Wait, I was thinking of another repo, let me check.

**Comment by retorquere** [comment]
Added in 5.1.2

**Comment by lezuber** [comment]
Thanks for your amazing work!
Looking forward to the feature.

**Comment by lezuber** [comment]
Hi again, no I figured out what you meant by "can set the Quick copy/drag-and-drop format to Cite Keys".
This setting seems to not affect the output of the atom plugin, only the drag and drop feature (is this one usable for atom in any way, btw?)
Have I seen it correctly that you gave pushed the changes already? I just updated the plugin and could not get it working so far. :/

**Comment by retorquere** [comment]
You can forget about my comment regarding `Quick copy/drag-and-drop`. When updating the atom plugin, you should see a `Citation keys` option in the config, that would do it. No need to do anything in BBT.

**Comment by lezuber** [comment]
Got it now. Works like a charm. Thank you!

**Comment by retorquere** [comment]
You're welcome
