### ISSUE TITLE
Feature request: port to vscode

### ISSUE THREAD

**Issue by atanasj** [retorquere/zotero-citations#48]
Hi,

It would be great to have a `vscode` version of this extension. I wish I knew how, but it is beyond my skill level!

Thanks for all your wonderful extensions!

**Comment by retorquere** [comment]
There's two extensions for vscode already; "Zotero LaTeX" and "Citation Picker for Zotero".

**Comment by atanasj** [comment]
Both often do not work as consistently as the `atom` extension you have written. It would be AWESOME if you were able to port this great extension to `vscode` for the functionality of the `zotero-better-bibtex` to be used with less glitches (no offense intended to the authors of those extensions).

**Comment by retorquere** [comment]
What kind of glitches? I'd prefer to get an existing extension fixed rather than adding more noise. Have you reported the glitches to the extension authors?

**Comment by retorquere** [comment]
A recent security update in Zotero interfered with some apps accessing the CAYW url; I know at least [mblode](https://github.com/mblode/vscode-zotero/issues/2) is actively working on a fix. If it's some other glitchiness I'd still prefer to work with those extension authors to get that resolved; I'll gladly help where I can, but

* I'm pretty sure they'd prefer to hear about problem so they can fix them
* vscode could well be subtly different than atom so maybe I'd run into the same glitchiness
* I try to stay away from GUI-related work (one of the reasons I'm so committed to LaTeX is that I can live my live in terminals with `vi` and makefiles)

**Comment by atanasj** [comment]
Understandable. Thanks for you reply and all your good work. Cheers.
