### ISSUE TITLE
Can I use this plugin with Jurism?

### ISSUE THREAD

**Issue by denismaier** [retorquere/zotero-citations#49]
This plugin does not work out of the box with Juris-M as Juris-M listens to a different port than Zotero. Can I adjust the port somehow?

**Comment by retorquere** [comment]
5.2.0 will allow you to select whether to connect to Zotero or JM

**Comment by denismaier** [comment]
Great. Thank you!

**Comment by denismaier** [comment]
Oh. But how do I choose Juris-M?

**Comment by retorquere** [comment]
From the extension settings in atom
