### ISSUE TITLE
picker shows up "behind" Atom on Mac full-screen mode

### ISSUE THREAD

**Issue by michaelkopech** [retorquere/zotero-citations#50]
I run Atom in full-screen mode on Mac OS Mojave. When I run the "pick" command, the picker does not show up, until I exit full-screen mode (or hit cmd-tab to switch to a different application/workspace). I run Atom in full-screen mode in Linux, as well, and have never had this problem. It just shows up right there, floating above the full-screen application. On Mac, it appears to float behind.

**Comment by retorquere** [comment]
I've put out a question on the Zotero forums, but I don't actually put up the picker myself, technically -- I ask Zotero to put up the picker and I await the results.

Does the same happen when you request the picker from Word with Word in full-screen?
