### ISSUE TITLE
Insertion of citation problem

### ISSUE THREAD

**Issue by mauriziopassariello** [retorquere/zotero-citations#57]
Hi, I have Zotero with BBT so I installed the package to insert citations into academic papers (written in markdown with Atom). I get the Zotero picker (with red borders) opened, I can identify the citation in Zotero that I would like inserted in the text; however, then the citation is not inserted into the text. What am I doing wrong?

**Comment by retorquere** [comment]
I'm not sure, I just tried and it works. Did you press enter after selecting the references?

**Comment by mauriziopassariello** [comment]
Thank you it works now!

On 18 Apr 2021, at 00:17, Emiliano Heyns ***@***.******@***.***>> wrote:



I'm not sure, I just tried and it works. Did you press enter after selecting the references?
